### ISSUE TITLE
http://html2pug.com is 502 bad gate way.please fix it,thanks

### ISSUE THREAD

**Issue by yuanyuanyuan** [izolate/html2pug-website#5]

**Comment by Hum4n01d** [comment]
Same issue here @izolate

**Comment by deepduggal** [comment]
Same as of August 2017

**Comment by qm3ster** [comment]
You can run [my fork](https://github.com/qm3ster/html2pug-website) locally, and I will probably host it sometime this week.

**Comment by izolate** [comment]
Thank you for reporting this @yuanyuanyuan @Hum4n01d @waxter013 @qm3ster. This has been fixed along with a refactoring of the website.
